### ISSUE TITLE
Twitter SSL error

### ISSUE THREAD

**Issue by jonas340** [gschurck/tradoge#11]
Hi!

I'm getting this error while using the script:

? Menu  Start TraDOGE
07:05:37 : Waiting for new DOGE tweet from Elon  (CTRL+C to stop)
ERROR :
 
Cannot connect to host api.twitter.com:443 ssl:True [Connection reset by peer]
 

It might be my extreme 1 second refresh rate doing it - should I just go with 5 or something?

**Comment by gschurck** [comment]
Yes, 1 second is probalby too low you might be blocked by Twitter.
