### ISSUE TITLE
Error: twint.token.RefreshTokenException: Could not find the Guest token in HTML

### ISSUE THREAD

**Issue by huang122124** [gschurck/tradoge#14]
I run this program and set every 1 seconds to fetch the data,but maybe blocked by twitter,I found many docs but can't fix it.Can you help me?

**Comment by gschurck** [comment]
1 second is very fast indeed. Is it an IP ban ? It still doesn't work if you wait a few hours ?

**Comment by gschurck** [comment]
> I run this program and set every 1 seconds to fetch the data,but maybe blocked by twitter,I found many docs but can't fix it.Can you help me?

1 second is very fast indeed. Is it an IP ban ? It still doesn't work if you wait a few hours ?

**Comment by huang122124** [comment]
I try many times and&nbsp; still limited by twitter



---Original---
From: "Guillaume ***@***.***&gt;
Date: Fri, May 21, 2021 20:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gschurck/tradoge] Error: twint.token.RefreshTokenException: Could not find the Guest token in HTML (#14)




  
I run this program and set every 1 seconds to fetch the data,but maybe blocked by twitter,I found many docs but can't fix it.Can you help me?
  
1 second is very fast indeed. Is it an IP ban ? It still doesn't work if you wait a few hours ?

**Comment by gschurck** [comment]
Could also be an error from twint package

Try
`pip uninstall twint`
`pip install --user --upgrade git+https://github.com/himanshudabas/twint.git@origin/twint-fixes#egg=twint`
