### ISSUE TITLE
Need help please

### ISSUE THREAD

**Issue by Lioncel888** [gschurck/tradoge#16]
Hi, I have followed transcript showed:

? Menu  Start TraDOGE
CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects' to stop)
sleeping for 1.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects'
sleeping for 8.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects'
sleeping for 27.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects'
sleeping for 64.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects'
sleeping for 125.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects'
sleeping for 216.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects'
sleeping for 343.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects'
sleeping for 512.0 secs
CRITICAL:root:twint.run:Twint:Feed:noData'globalObjects'
sleeping for 729.0 secs

I'm not sure what is wrong.

**Comment by gschurck** [comment]
Hello, try this please `pip3 install --user --upgrade git+https://github.com/himanshudabas/twint.git@origin/twint-fixes#egg=twint`
