### ISSUE TITLE
Problème

### ISSUE THREAD

**Issue by Asted91** [gschurck/tradoge#18]
Bonjour Guillaume tout d'abord merci pour cette idée génialissime, j'ai un soucis avec la version Windows

ERROR :

Cannot connect to host api.twitter.com:443 ssl:True [Connect call failed ('104.244.42.2', 443)]

←[KRestarting the program in  |←[33m$←[39m←[33m$←[39m←[33m$←[39m

j'ai essayé de jouer avec le tweet frequency de 1 a 60 voir 90 mais rien n'y fait, ça ferme le programme a chaque fois, aurait tu une solution ? merci bonne continuation !

**Comment by gschurck** [comment]
Bonjour, c'est étrange. essaie `pip3 install --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint
`
