### ISSUE TITLE
help

### ISSUE THREAD

**Issue by duchuAz** [gschurck/tradoge#27]
Traceback (most recent call last):
  File "tradoge.py", line 594, in <module>
    main()
  File "tradoge.py", line 501, in main
    if last_tweet.id == tweets[0].id:
IndexError: list index out of range

**Comment by gschurck** [comment]
The bot is broken due to changes on Twitter, I'm working on an update, stay tuned.

**Comment by duchuAz** [comment]
thank you

**Comment by duchuAz** [comment]
looking forward to new updates from you

**Comment by gschurck** [comment]
Yep, you can set the repo as watched to be notified by new updates.
