### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by bernardops22** [gschurck/tradoge#4]
After setting up the API and connecting to the Binance account the following message appears:

`Traceback (most recent call last):
  File "tradoge.py", line 382, in <module>
    main()
  File "tradoge.py", line 297, in main
    menu(new_config, client)
  File "tradoge.py", line 117, in menu
    doge_balance = client.get_asset_balance(asset='DOGE')['free']
TypeError: 'NoneType' object is not subscriptable`

**Comment by gschurck** [comment]
> After setting up the API and connecting to the Binance account the following message appears:
> 
> `Traceback (most recent call last): File "tradoge.py", line 382, in <module> main() File "tradoge.py", line 297, in main menu(new_config, client) File "tradoge.py", line 117, in menu doge_balance = client.get_asset_balance(asset='DOGE')['free'] TypeError: 'NoneType' object is not subscriptable`

Do you use the Windows executable file or python script ?
Do you have the 'Connected on Binance' green message on login ?

**Comment by bernardops22** [comment]
I used the Python Script and it showed the connected message. Is it possible that the error is shown because I don´t have any currency/coin in Binance?

**Comment by gschurck** [comment]
I don't think, because I tried with currency I don't have and it displays 0 for the amount and no error

**Comment by gschurck** [comment]
What is you API configuration on Binance ?
Here is mine :
![image](https://user-images.githubusercontent.com/21091232/108258692-99703980-7160-11eb-83a1-d99508905f7b.png)

**Comment by bernardops22** [comment]
Same thing here. I am looking for the error too.

**Comment by bernardops22** [comment]
How is set your config file?

**Comment by gschurck** [comment]
Normally in the menu you can choose your configuration and it writes in file. But if there is an error in menu it's complicated.
Try with to print `client.get_asset_balance(asset='DOGE')` without `['free']`

**Comment by gschurck** [comment]
And try to replace doge with other cryptocurrencies

**Comment by bernardops22** [comment]
Without `['free']` the two variables are set to "None" so there will be an error in `doge_value = float(doge_balance) * float(price)`

**Comment by gschurck** [comment]
It seems like you are just not connected to your account. I think the way I check the connection on Binance is not good, it only pings the server via your `client` connection. I didn't think it would work even if you are not connected to your account.
Try : 
`print(client.get_account())`

It will show something like that if you have access to your account : 
![image](https://user-images.githubusercontent.com/21091232/108269467-4ef5b980-716e-11eb-8992-765de5435468.png)

**Comment by bernardops22** [comment]
The balances are clear `{'makerCommission': 10, 'takerCommission': 10, 'buyerCommission': 0, 'sellerCommission': 0, 'canTrade': True, 'canWithdraw': True, 'canDeposit': True, 'updateTime': 1613432228552, 'accountType': 'SPOT', 'balances': [], 'permissions': ['SPOT']}`

**Comment by gschurck** [comment]
It's really strange ! Because it looks like you are connected to your account, but we don't see your balances..
I think the problem probably comes from your account more than TraDOGE.
I don't know if there are some limitations on Binance. Maybe you can try to send a little amount of a currency on your Binance account, if you really have 0 in every currencies.
And maybe try to create new API keys (type RESET when typing your password on login to set new API keys)

**Comment by bernardops22** [comment]
The program is finally working. The problem was not in your code but simply because I did not have any currency in my Binance account. I will follow closely your good work! Cheers

**Comment by MorphyHu** [comment]
pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint\n
