### ISSUE TITLE
Use max amount

### ISSUE THREAD

**Issue by Dutchblue020** [gschurck/tradoge#6]
Hi,

Is it in the Windows version possible to setup the max of fiat that can be used in place of the max dogecoin? (for example max 100 EUR in place of max 100 DOGE)

**Comment by gschurck** [comment]
Hello, it is available only for USDT and BUSD for now. Btw it is recommended to trade in crypto-crypto instead of crypto-fiat. I will implement this for BTC and EUR later. Just swap your EUR for USDT and you can.

**Comment by Dutchblue020** [comment]
Thanks for the tip, switched to BUSD.
Can now use a max amount in place of DOGE.
