### ISSUE TITLE
twitter removed timeline

### ISSUE THREAD

**Issue by cr0co** [gschurck/tradoge#7]
hey

i read that twitter disabled the url https://twitter.com/i/search/timeline

im getting error
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)

how can i fix this ?

**Comment by gschurck** [comment]
Hello,
Try to reinstall twint with this command `pip3 install --user --upgrade git+https://github.com/himanshudabas/twint.git@origin/twint-fixes#egg=twint`

It fixes some problems
